-- DEPT : PK_DEPT (부모)
-- EMP  : PK_EMP, FK_DEPTNO (자식)
-- 삭제순서 : 자식 먼저 삭제
DROP TABLE EMP;
DROP TABLE DEPT;
DROP TABLE BONUS;
DROP TABLE SALGRADE;


-- 학교 테이블
DROP TABLE SCHOOL;
CREATE TABLE SCHOOL(
    SCHOOL_CODE     NUMBER,  -- PK
    SCHOOL_NAME     VARCHAR2(10 BYTE));

-- 학생 테이블
DROP TABLE STUDENT;
CREATE TABLE STUDENT(
    STUDENT_NO      NUMBER(5),  -- PK
    SCHOOL_CODE     NUMBER,  -- FK (관계 맺는 PK와 반드시 같은 타입)
    NAME            VARCHAR2(10 BYTE));

-- 제약조건(기본키, 외래키) 추가하기
ALTER TABLE SCHOOL ADD CONSTRAINT SCHOOL_PK PRIMARY KEY(SCHOOL_CODE);
ALTER TABLE STUDENT ADD CONSTRAINT STUDENT_PK PRIMARY KEY(STUDENT_NO);
ALTER TABLE STUDENT ADD CONSTRAINT SCHOOL_STUDENT_FK FOREIGN KEY(SCHOOL_CODE) REFERENCES SCHOOL(SCHOOL_CODE);


-- DDL : Data Definition Language
-- 데이터 정의어
-- 1. CREATE문 : 데이터베이스 객체 생성
-- 2. DROP문   : 데이터베이스 객체 삭제
-- 3. ALTER문  : 데이터베이스 객체 수정









