USE SPRING;  -- 지금부터 SPRING 스키마에서 작업한다.

DROP TABLE IF EXISTS NOTICE;  -- NOTICE 테이블이 있으면 삭제한다. IF가 반드시 있어야 한다.

CREATE TABLE NOTICE
(
    NO BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(100),
    CONTENT VARCHAR(100),
    CREATED DATETIME,
    LASTMODIFIED DATETIME
);

INSERT INTO NOTICE(TITLE, CONTENT, CREATED, LASTMODIFIED) VALUES ('공지1', '내용1', NOW(), NOW());
INSERT INTO NOTICE(TITLE, CONTENT, CREATED, LASTMODIFIED) VALUES ('공지2', '내용2', NOW(), NOW());
INSERT INTO NOTICE(TITLE, CONTENT, CREATED, LASTMODIFIED) VALUES ('공지3', '내용3', NOW(), NOW());
INSERT INTO NOTICE(TITLE, CONTENT, CREATED, LASTMODIFIED) VALUES ('공지4', '내용4', NOW(), NOW());
INSERT INTO NOTICE(TITLE, CONTENT, CREATED, LASTMODIFIED) VALUES ('공지5', '내용5', NOW(), NOW());
INSERT INTO NOTICE(TITLE, CONTENT, CREATED, LASTMODIFIED) VALUES ('공지6', '내용6', NOW(), NOW());
INSERT INTO NOTICE(TITLE, CONTENT, CREATED, LASTMODIFIED) VALUES ('공지7', '내용7', NOW(), NOW());
INSERT INTO NOTICE(TITLE, CONTENT, CREATED, LASTMODIFIED) VALUES ('공지8', '내용8', NOW(), NOW());
INSERT INTO NOTICE(TITLE, CONTENT, CREATED, LASTMODIFIED) VALUES ('공지9', '내용9', NOW(), NOW());
INSERT INTO NOTICE(TITLE, CONTENT, CREATED, LASTMODIFIED) VALUES ('공지10', '내용10', NOW(), NOW());
INSERT INTO NOTICE(TITLE, CONTENT, CREATED, LASTMODIFIED) VALUES ('공지11', '내용11', NOW(), NOW());
INSERT INTO NOTICE(TITLE, CONTENT, CREATED, LASTMODIFIED) VALUES ('공지12', '내용12', NOW(), NOW());
INSERT INTO NOTICE(TITLE, CONTENT, CREATED, LASTMODIFIED) VALUES ('공지13', '내용13', NOW(), NOW());
INSERT INTO NOTICE(TITLE, CONTENT, CREATED, LASTMODIFIED) VALUES ('공지14', '내용14', NOW(), NOW());
INSERT INTO NOTICE(TITLE, CONTENT, CREATED, LASTMODIFIED) VALUES ('공지15', '내용15', NOW(), NOW());
INSERT INTO NOTICE(TITLE, CONTENT, CREATED, LASTMODIFIED) VALUES ('공지16', '내용16', NOW(), NOW());
INSERT INTO NOTICE(TITLE, CONTENT, CREATED, LASTMODIFIED) VALUES ('공지17', '내용17', NOW(), NOW());
INSERT INTO NOTICE(TITLE, CONTENT, CREATED, LASTMODIFIED) VALUES ('공지18', '내용18', NOW(), NOW());
INSERT INTO NOTICE(TITLE, CONTENT, CREATED, LASTMODIFIED) VALUES ('공지19', '내용19', NOW(), NOW());
INSERT INTO NOTICE(TITLE, CONTENT, CREATED, LASTMODIFIED) VALUES ('공지20', '내용20', NOW(), NOW());
COMMIT;