DROP TABLE PRODUCT;

CREATE TABLE PRODUCT (
    PNO     NUMBER,
    PNAME   VARCHAR2(20),
    PRICE   NUMBER,
    PDATE   DATE
);

ALTER TABLE PRODUCT
    ADD CONSTRAINT PRODUCT_PK
        PRIMARY KEY(PNO);

DROP SEQUENCE PRODUCT_SEQ;
CREATE SEQUENCE PRODUCT_SEQ NOCACHE;


-- PRODUCT 테이블 조회
SELECT * FROM PRODUCT;
