DROP TABLE CONTACT;
CREATE TABLE CONTACT
(
    NO NUMBER PRIMARY KEY,
    NAME VARCHAR2(100),
    TEL VARCHAR2(100),
    ADDRESS VARCHAR2(100),
    BIRTHDAY VARCHAR2(10)
);
DROP SEQUENCE CONTACT_SEQ;
CREATE SEQUENCE CONTACT_SEQ NOCACHE;











CREATE TABLE BOARD
(
    NO NUMBER PRIMARY KEY,
    WRITER VARCHAR2(100),
    TITLE VARCHAR2(100),
    CONTENT VARCHAR2(100),
    CREATED VARCHAR2(10),
    LASTMODIFIED VARCHAR2(10)
);
CREATE SEQUENCE BOARD_SEQ NOCACHE;

DROP TABLE MEMBER;
CREATE TABLE MEMBER
(
	NO NUMBER PRIMARY KEY,
	ID VARCHAR2(32) NOT NULL UNIQUE,
	PW VARCHAR2(64) NOT NULL,  -- 암호화된 비밀번호 최대 64바이트
	NAME VARCHAR2(64),
	EMAIL VARCHAR2(100) NOT NULL UNIQUE,
	REGDATE DATE
);

DROP SEQUENCE MEMBER_SEQ;
CREATE SEQUENCE MEMBER_SEQ INCREMENT BY 1 START WITH 1 NOCYCLE NOCACHE;

SELECT * FROM MEMBER;