DROP TABLE MEMBER;
CREATE TABLE MEMBER
(
    MEMBER_NO NUMBER PRIMARY KEY,
    ID VARCHAR2(100) NOT NULL UNIQUE,
    NAME VARCHAR2(100),
    GENDER VARCHAR2(3),
    ADDRESS VARCHAR2(100)
);

INSERT INTO MEMBER VALUES(MEMBER_SEQ.NEXTVAL, 'ID1', '이름1', '남', '서울시1');
INSERT INTO MEMBER VALUES(MEMBER_SEQ.NEXTVAL, 'ID2', '이름2', '여', '서울시2');
INSERT INTO MEMBER VALUES(MEMBER_SEQ.NEXTVAL, 'ID3', '이름3', '남', '서울시3');
INSERT INTO MEMBER VALUES(MEMBER_SEQ.NEXTVAL, 'ID4', '이름4', '여', '서울시4');
INSERT INTO MEMBER VALUES(MEMBER_SEQ.NEXTVAL, 'ID5', '이름5', '남', '서울시5');
INSERT INTO MEMBER VALUES(MEMBER_SEQ.NEXTVAL, 'ID6', '이름6', '여', '서울시6');
INSERT INTO MEMBER VALUES(MEMBER_SEQ.NEXTVAL, 'ID7', '이름7', '남', '서울시7');
INSERT INTO MEMBER VALUES(MEMBER_SEQ.NEXTVAL, 'ID8', '이름8', '여', '서울시8');
INSERT INTO MEMBER VALUES(MEMBER_SEQ.NEXTVAL, 'ID9', '이름9', '남', '서울시9');
INSERT INTO MEMBER VALUES(MEMBER_SEQ.NEXTVAL, 'ID10', '이름10', '여', '서울시10');
INSERT INTO MEMBER VALUES(MEMBER_SEQ.NEXTVAL, 'ID11', '이름11', '남', '서울시11');
INSERT INTO MEMBER VALUES(MEMBER_SEQ.NEXTVAL, 'ID12', '이름12', '여', '서울시12');
INSERT INTO MEMBER VALUES(MEMBER_SEQ.NEXTVAL, 'ID13', '이름13', '남', '서울시13');
INSERT INTO MEMBER VALUES(MEMBER_SEQ.NEXTVAL, 'ID14', '이름14', '여', '서울시14');
INSERT INTO MEMBER VALUES(MEMBER_SEQ.NEXTVAL, 'ID15', '이름15', '남', '서울시15');
INSERT INTO MEMBER VALUES(MEMBER_SEQ.NEXTVAL, 'ID16', '이름16', '여', '서울시16');
INSERT INTO MEMBER VALUES(MEMBER_SEQ.NEXTVAL, 'ID17', '이름17', '남', '서울시17');
INSERT INTO MEMBER VALUES(MEMBER_SEQ.NEXTVAL, 'ID18', '이름18', '여', '서울시18');
INSERT INTO MEMBER VALUES(MEMBER_SEQ.NEXTVAL, 'ID19', '이름19', '남', '서울시19');
INSERT INTO MEMBER VALUES(MEMBER_SEQ.NEXTVAL, 'ID20', '이름20', '여', '서울시20');
INSERT INTO MEMBER VALUES(MEMBER_SEQ.NEXTVAL, 'ID21', '이름21', '남', '서울시21');
INSERT INTO MEMBER VALUES(MEMBER_SEQ.NEXTVAL, 'ID22', '이름22', '여', '서울시22');
INSERT INTO MEMBER VALUES(MEMBER_SEQ.NEXTVAL, 'ID23', '이름23', '남', '서울시23');
INSERT INTO MEMBER VALUES(MEMBER_SEQ.NEXTVAL, 'ID24', '이름24', '여', '서울시24');
INSERT INTO MEMBER VALUES(MEMBER_SEQ.NEXTVAL, 'ID25', '이름25', '남', '서울시25');
INSERT INTO MEMBER VALUES(MEMBER_SEQ.NEXTVAL, 'ID26', '이름26', '여', '서울시26');
INSERT INTO MEMBER VALUES(MEMBER_SEQ.NEXTVAL, 'ID27', '이름27', '남', '서울시27');
INSERT INTO MEMBER VALUES(MEMBER_SEQ.NEXTVAL, 'ID28', '이름28', '여', '서울시28');
INSERT INTO MEMBER VALUES(MEMBER_SEQ.NEXTVAL, 'ID29', '이름29', '남', '서울시29');
INSERT INTO MEMBER VALUES(MEMBER_SEQ.NEXTVAL, 'ID30', '이름30', '여', '서울시30');
COMMIT;

DROP TABLE BOARD_ATTACH;
DROP TABLE BOARD;

CREATE TABLE BOARD
(
    BOARD_NO NUMBER PRIMARY KEY,
    TITLE VARCHAR2(100) NOT NULL,
    CONTENT VARCHAR2(100),
    WRITER VARCHAR2(100),
    IP VARCHAR2(40),
    CREATED DATE,
    LASTMODIFIED DATE
);
CREATE TABLE BOARD_ATTACH
(
    UUID VARCHAR2(32) PRIMARY KEY,  -- 저장된 첨부파일명을 의미함.
    PATH VARCHAR2(300),
    ORIGIN VARCHAR2(300),
    FILETYPE VARCHAR2(1) DEFAULT 'I',  -- 이미지를 기본값으로 설정.
    BOARD_NO NUMBER REFERENCES BOARD(BOARD_NO)
);

DROP SEQUENCE MEMBER_SEQ;
CREATE SEQUENCE MEMBER_SEQ NOCACHE;
DROP SEQUENCE BOARD_SEQ;
CREATE SEQUENCE BOARD_SEQ NOCACHE;
